### PR TITLE
general code reformat (only cosmetic changes, e.g.: use spaces for indentation)

### PR DESCRIPTION
**Pull request by dcominottim**
@pryzach Thank you so much for all the improvements you have recently made to upstream! As we had discussed sometime ago, I intended to make a code reformat in order to make the code a lot easier to read on GitHub and more consistent within IDEs by means of replacing all Tab characters with Spaces. Although most files have been changed, I have tried not to touch anything but Tabs and Spaces by using IntelliJ IDEA's option to keep the project's own code style. Please feel free to reject this PR if you think the changes are unnecessary or to point out any inconsistencies or mistakes (I have manually verified a lot of files, though).

### CODE REVIEW

**Comment by pryzach** [comment]
@dcominottim Thank you very much for sharing this. I want to go over it this weekend, I've created new branch called "indentation" - can you merge there ?

**Comment by dcominottim** [comment]
@pryzach I am truly sorry for not noticing your reply sooner. My GitHub account was linked to an e-mail address that I do not really use anymore, and, therefore, I totally missed your reply. I will definitely go over this task this weekend. Thank you so much for your patience and good will. (I will also get in touch via e-mail ASAP.)

**Comment by dcominottim** [comment]
@pryzach I believe I currently lack the required permission in order to merge directly into your indentation branch. Do you want me to merge into the indentation branch from my clone and then submit a new pull request or is it possible to grant me commit permission just to your indentation branch?

**Comment by pryzach** [comment]
@dcominottim No worries, glad to hear that you are still motivated to work on this project.
I've added you to the collaborators, this should allow you commit your development to "indentation" branch. Please let me know if further assistance is required.

**Pull request merged**
